### ISSUE TITLE
New feature for morse decoder.

### ISSUE THREAD

**Issue by steveiliop56** [sergoum/pico_morse#1]
Could you add a script that will run on an other pico and it will decode the morse messages. eg with connection a data pin and a ground?

**Comment by sergi0g** [comment]
Do you mean using another pin as an output and connecting it to another pico?

**Comment by steveiliop56** [comment]
Yes

**Comment by sergi0g** [comment]
Such a feature would be hard to implement as precise synchronization is required. I am not going to be updating this project any more. If you want to submit a PR with the feature, please do.

**Comment by steveiliop56** [comment]
No
